/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/premium': typeof PremiumRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/premium': typeof PremiumRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/premium': typeof PremiumRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/premium' | '/recent' | '/settings' | '/tool/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/premium' | '/recent' | '/settings' | '/tool/$slug'
  id: '__root__' | '/' | '/premium' | '/recent' | '/settings' | '/tool/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PremiumRoute: typeof PremiumRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PremiumRoute: PremiumRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  ToolSlugRoute: ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
